# Generated by Django 4.1.5 on 2023-01-27 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='product',
            new_name='order',
        ),
    ]
